## Each new term in the Fibonacci sequence is generated by adding the previous two terms.
## By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms

## Generate a list of all Fibonacci numbers that don't exceed a certain value via iteration. 
def fibNotAbove(largest, first, second):
    fibs = []
    while first < largest:
        fibs.append(first)
        
        tmp = first
        first = second
        second = second + tmp

    return fibs

## Return all even items in a list
def findEven(n):
    return [x for x in n if x%2 == 0]

## Finding the sum of all even-valued items in the Fibonacci sequence below 4,000,000
def main():
    print(sum(findEven(fibNotAbove(4000000, 1, 2))))

main()
